// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  profileSidebar: [
    {
      type: 'doc',
      label: 'Overview',
      id: 'intro',
    },
  ],
  portfolioSidebar: [
    {
      type: 'doc',
      label: 'Portfolio Introduction',
      id: 'portfolio-intro',
    },
    {
      type: 'category',
      label: 'Documentation Tooling',
      items: [
              {
                type: 'doc',
                label: 'Introduction',
                id: 'documentation-tooling/intro',
              },
              {
                type: 'doc',
                label: 'Getting Started',
                id: 'documentation-tooling/getting-started',
              },
              {
                type: 'category',
                label: 'Reference',
                items: ['documentation-tooling/reference/get-items','documentation-tooling/reference/post-items'],
              },
            ],
    },
    {
      type: 'category',
      label: 'API Documentation',
      items: [
                 {
      type: 'doc',
      label: 'Introduction',
      id: 'api-documentation/intro',
    },
    {
      type: 'doc',
      label: 'Getting Started',
      id: 'api-documentation/getting-started',
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
              {
                type: 'doc',
                id: 'api-documentation/reference/payout',
                label: 'Initiate Payout',
              },
              {
                type: 'doc',
                id: 'api-documentation/reference/balance',
                label: 'Check Balance',
              },
              {
                type: 'doc',
                id: 'api-documentation/reference/listcards',
                label: 'List Gift Cards',
              },
            ],
      },
            ],
    },
  ],
   /* toolingSidebar: [
    'documentation-tooling/intro',
    {
      type: 'category',
      label: 'Introduction',
      items: ['tutorial-basics/create-a-document'],
    },
  ],*/
   /*toolingSidebar: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'documentation-tooling/intro',
    },
    {
      type: 'doc',
      label: 'Getting Started',
      id: 'documentation-tooling/getting-started',
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['documentation-tooling/reference/get-items','documentation-tooling/reference/post-items'],
    },
  ],*/
   /* apiSidebar: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'api-documentation/intro',
    },
    {
      type: 'doc',
      label: 'Getting Started',
      id: 'api-documentation/getting-started',
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
              {
                type: 'doc',
                id: 'api-documentation/reference/payout',
                label: 'Initiate Payout',
              },
              {
                type: 'doc',
                id: 'api-documentation/reference/balance',
                label: 'Check Balance',
              },
              {
                type: 'doc',
                id: 'api-documentation/reference/listcards',
                label: 'List Gift Cards',
              },
            ],
    },*/
    /*{
      type: 'category',
      label: 'Setting Up',
      items: ['tutorial-basics/create-a-document'],
    },*/
  //],
   
};

export default sidebars;
