name: Vale Linting

on:
  push:
    branches:
      - portfolio-site

jobs:
  check-vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: actions/checkout@v4

      - name: Run Vale Check
        run: errata-ai/vale-action@v2.1.1
