name: Vale Linting

on:
  push:
    branches:
      - portfolio-site

jobs:
  check-vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: 'echo "Repository: ${{ github.repository }}"'
